### ISSUE TITLE
How to run ades2mpc.cpp

### ISSUE THREAD

**Issue by dpieterse** [Bill-Gray/lunar#15]
Dear Bill Gray,

May I ask how one runs the ades2mpc.cpp script? When I try to 'make' it, I'm getting errors about undefined references to create_mpc_packed_desig, net_name_to_byte_code, extract_date_from_mpc_report and several other functions. Does the script depend on other scripts in the lunar package?

Kind regards,
Danielle

**Comment by Bill-Gray** [comment]
`ades2mpc.cpp` just has some underlying functions to read in ADES data and produce something that resembles "traditional" 80-column MPC data.  There's an example program,  `adestest.cpp`,  that demonstrates usage of those functions/could serve as a conversion utility/gives me a way of testing the ADES parsing.  So run

`make adestest`

to build the converter program.

Your comment made me realize that there's no real top-level,  what-am-I-looking-at documentation in either `ades2mpc.cpp` or `adestest.cpp`.  (If I documented my code properly,  people would wonder if I was really a programmer.)  If you do a 'git pull',  you'll see that I've just added a few sentences of that sort to both files.

Note the warnings about this _not_ being exactly 80-column data of the sort MPC would want to see.  To support the greater precision for times and RA/decs,  I modified the formats.  Actually,  I should probably provide a "output strictly MPC-compatible astrometry,  even though it mangles precision" option.  Not something I'd have any use for,  but the result would still be useful in low-precision applications.

**Comment by dpieterse** [comment]
Thank you so much for your quick response! And thank you for explaining the changes between the format it produces and the 80-column MPC format. I intend to use the script for analysis purposes, as running my existing scripts on your format will require much fewer changes to my code than it would running it on the ADES format file that I intend to use as input. So your code is much appreciated!
