### ISSUE TITLE
Bug: extra columns in astcheck output

### ISSUE THREAD

**Issue by dpieterse** [Bill-Gray/lunar#19]
When running astcheck in a folder that (only) contains mpcorb.sof and ObsCodes.html, I get the specified output. However, if there is also an MPCORB.DAT file in that folder, I get four additional columns. Doesn't matter if I'm running astcheck on an MPC-formatted observation file or if I'm using it with the -c option, like in you're example "astcheck -c 2022apr3.1415 292.653 -7.653 E12 -r7200". 

The four columns are related to the MPCORB column data. For your -c option example, the first line is supposed to be outputted like:
```
                           RA  (J2000)  dec       mag   dRA/dt    dDec/dt
         509              293.070380 -08.653678  14.31    0.5572   0.3008
```
where if MPCORB.DAT is also in the folder, I instead get:
```
                           RA  (J2000)  dec       mag   dRA/dt    dDec/dt
         509              293.070380 -08.653678  14.31    0.5572   0.3008 0000  3539  64 1903-2021
```
This seems like a bug to me.

**Comment by Bill-Gray** [comment]
One person's bug is another person's feature.  (Except I think a lot of people will share your viewpoint.  So it's probably closer to one person's feature being seven people's bug.)

Short version : I've just posted an update that fixes this.  Pull new code,  rebuild,  and you should be in business.

Long version : I got a request recently for two new features for astcheck.  One allows you to specify an RA/dec,  time,  angular distance,  and location,  and get a list of all objects within the specified distance of that RA/dec as seen from that location (run astcheck without command line arguments to see this described).

The second was to output some basic data from MPCORB.DAT,  to supplement the information astcheck already gave for each object.  This defaulted to showing the MPC's four-hex-digit digest of orbital characteristics,  the number of observations,  number of oppositions,  and timespan of the observed arc.

You can still get that by adding `-e "162,4;118,19"`,  telling astcheck to display four bytes starting at column 162 and nineteen bytes starting at column 118.   The gent who asked for this feature was a little unclear as to which data from MPCORB.DAT he'd be needing,  so I left it flexible.

I'd left the above `-e "162,4:118,19"` as the default.  In hindsight,  most people won't want any of that,  so I've reset the default back to "don't show me MPCORB.DAT info".

**Comment by dpieterse** [comment]
Dear Bill, thank you very much for your quick response and clear explanation!
