### ISSUE TITLE
make integrat

### ISSUE THREAD

**Issue by knservis** [Bill-Gray/lunar#24]
https://github.com/Bill-Gray/lunar/blob/06680af02445218bd54f5df0df0013149b8a674c/integrat.cpp#L1191

The above line stops compilation via `make intergat` with:

```
g++ -Wextra -Wall -O3 -pedantic -Werror -c -I ~/include integrat.cpp                                                                                             0.509 In file included from integrat.cpp:25:                                                                                                                           0.509 integrat.cpp: In function 'int main(int, const char**)':                                                                                                         0.509 integrat.cpp:1191:34: error: suggest parentheses around assignment used as truth value [-Werror=parentheses]                                                     0.509  1191 |                assert( n_written = n_xyzs);
       |                        ~~~~~~~~~~^~~~~~~~
cc1plus: all warnings being treated as errors
make: *** [makefile:277: integrat.o] Error 1
```

Either:
1. I have missed something
2. The line needs to change to not have an assignment (but a test with `==`)
3. The warning to not be converted to errors

Can you help with 1 or can I help with 2,3?

Thank you

**Comment by Bill-Gray** [comment]
(2) is correct.  Thanks for pointing this out.  My usual development machine has gcc version 9.4.  On occasion,  when I've used later versions,  I've noticed that they are smarter about warning you about things such as this.  I should upgrade.

The code was multiply wrong.  I would usually have declared `n_written` to be `const`.  Had I done so,  even 9.4 would have told me I was attempting to change a `const` variable.  Also,  I was comparing a `size_t` value to an `int` value with no cast used.

`n_written` is not actually used,  so resetting it would have no effect.    So the code ran Just Fine.  However,  the assert() is present to check that all the data was written to the output file.  With `==`,  it will do that check.  With `=`,  it will never be triggered.

Thanks for the fix!
